# see me at: http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyterhub/jupyterhub/master/docs/rest-api.yml#/default
swagger: '2.0'
info:
  title: JupyterHub
  description: The REST API for JupyterHub
  version: 0.9.0dev
  license:
    name: BSD-3-Clause
schemes:
  [http, https]
securityDefinitions:
  token:
    type: apiKey
    name: x-authorization
    in: header
security:
  - token: []
basePath: /hub
host: 127.0.0.1:8000
produces:
  - application/json
consumes:
  - application/json
paths:
  /api/users/{name}/servers/{server_name}:
    post:
      summary: Start a user's single-user named-server notebook server
      parameters:
        - name: x-authorization
          description: token auth 
          in: header
          required: true
          type: string
        - name: name
          description: username
          in: path
          required: true
          type: string
        - name: server_name
          description: name given to a named-server
          in: path
          required: true
          type: string
        - name: options
          description: |
            Spawn options can be passed as a JSON body
            when spawning via the API instead of spawn form.
            The structure of the options
            will depend on the Spawner's configuration.
          in: body
          required: false
          schema:
            type: object
      responses:
        '201':
          description: The user's notebook named-server has started
        '202':
          description: The user's notebook named-server has not yet started, but has been requested
    delete:
      summary: Stop a user's named-server
      parameters:
        - name: x-authorization
          description: token auth 
          in: header
          required: true
          type: string
        - name: name
          description: username
          in: path
          required: true
          type: string
        - name: server_name
          description: name given to a named-server
          in: path
          required: true
          type: string
        - name: remove
          description: |
            Whether to fully remove the server, rather than just stop it.
            Removing a server deletes things like the state of the stopped server.
          in: body
          required: false
          schema:
            type: boolean
      responses:
        '204':
          description: The user's notebook named-server has stopped
        '202':
          description: The user's notebook named-server has not yet stopped as it is taking a while to stop
    get:
      summary: get status of  a user's named-server
      parameters:
        - name: x-authorization
          description: token auth 
          in: header
          required: true
          type: string
        - name: name
          description: username
          in: path
          required: true
          type: string
        - name: server_name
          description: name given to a named-server
          in: path
          required: true
          type: string
      responses:
        '200':
          description: The user's notebook named-server status
          schema:
            $ref: '#/definitions/Server'

definitions:
  Msg:
    type: object
    properties:
      status:
        type: integer
        description: 状态码,沿用jupyterhub的设计,目前是与http code保持一样 如400,401 200
      message:
        type: string
        description: 提示信息,主要是错误信息,可能为空
        
        
        
  Server:
    type: object
    properties:
      active:
        type: boolean
        description: 是否有效，如果为False，则启动失败
      name:
        type: string
        description: The server's name. The user's default server has an empty name ('')
      ready:
        type: boolean
        description: |
          Whether the server is ready for traffic.
          Will always be false when any transition is pending.
      pending:
        type: string
        enum: ["spawn", "stop", null]
        description: |
          The currently pending action, if any.
          A server is not ready if an action is pending.
      url:
        type: string
        description: |
          The URL where the server can be accessed
          (typically /user/:name/:server.name/).
      progress_url:
        type: string
        description: |
          The URL for an event-stream to retrieve events during a spawn.
      started:
        type: string
        format: date-time
        description: UTC timestamp when the server was last started.
      last_activity:
        type: string
        format: date-time
        description: UTC timestamp last-seen activity on this server.
      state:
        type: object
        description: Arbitrary internal state from this server's spawner.  Only available on the hub's users list or get-user-by-name method, and only if a hub admin.  None otherwise.
